#!/usr/bin/env node
// Reconstroi pokemon_roster.json a partir das páginas wiki dos 10 clãs.
// Mantém ids existentes (preserva pokes já registrados); adiciona novos com kebab-case.
// Inclui campos: id, name, tier, clans, role (PvE), pvpRole (PvP), elements.

const fs = require("fs");
const path = require("path");

const ROSTER_PATH = path.join(__dirname, "..", "pxg_app", "src", "data", "pokemon_roster.json");
const POKEMON_PATH = path.join(__dirname, "..", "pxg_app", "src", "data", "pokemon.json");

// Mapeamento role wiki → role tipado
function mapRole(wikiRole) {
  if (!wikiRole || wikiRole === "none" || wikiRole.toLowerCase() === "none") return null;
  const r = wikiRole.toLowerCase().trim();
  // Combos (ex: "BDD/OTDD"): pega o primeiro
  const first = r.split("/")[0].trim();
  if (first === "bdd") return "burst_dd";
  if (first === "otdd") return "otdd";
  if (first === "offensive tank" || first === "offtank") return "offensive_tank";
  if (first === "tank") return "tank";
  if (first === "speedster") return "speedster";
  if (first === "support" || first === "support overtime" || first === "supportot" || first === "support ot") return "support";
  if (first === "disrupter") return "disrupter";
  return null;
}

// Tier ordering: menor é mais forte. T1A < T1B < T1C < T1H < TM/TR < T2 < T3
const TIER_RANK = { T1A: 1, T1B: 2, T1C: 3, T1H: 4, TM: 5, TR: 6, T2: 7, T3: 8 };

// Dados extraídos das páginas wiki dos clãs.
// Formato: clan → array of {name, tier, pve, pvp}
const wikiData = {
  volcanic: [
    { name: "Shiny Magmar", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Arcanine", tier: "T1B", pve: "BDD/OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Charizard", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Charizard X", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Mega Charizard Y", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Ninetales", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Hisuian Arcanine", tier: "T1C", pve: "none", pvp: "BDD" },
    { name: "Alolan Marowak", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Shiny Typhlosion", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Magcargo", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Houndoom", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Mega Blaziken", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Torkoal", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Shiny Infernape", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Magmortar", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Heatran", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Delphox", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Cinderace", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Charizard (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Alolan Marowak (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Mega Houndoom (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Torkoal (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Magmortar (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Charizard (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Shiny Houndoom", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Chandelure", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Chandelure", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Heatmor", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Pyroar", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Ninetales", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Arcanine", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Rapidash", tier: "T2", pve: "none", pvp: "Support" },
    { name: "Magmar", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Flareon", tier: "T2", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Hisuian Typhlosion", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Houndoom", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Magby", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Mega Camerupt", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Torkoal", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Castform", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Infernape", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Darmanitan", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Galarian Darmanitan", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Galarian Zen Darmanitan", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Volcarona", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Pyroar", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Pyroar Female", tier: "T2", pve: "Tank", pvp: "Tank" },
    { name: "Talonflame", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Turtonator", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Cinderace", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Charizard", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Rapidash", tier: "T3", pve: "Speedster", pvp: "BDD" },
    { name: "Flareon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Typhlosion", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Magcargo", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Blaziken", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Camerupt", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Simisear", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Chandelure", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Heatmor", tier: "T3", pve: "none", pvp: "Support" },
  ],
  raibolt: [
    { name: "Shiny Electabuzz", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Manectric", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Raichu", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Alolan Golem", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Magneton", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Lanturn", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Ampharos", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Ampharos", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Mega Manectric", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Luxray", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Shiny Magnezone", tier: "T1C", pve: "OTDD", pvp: "BDD" },
    { name: "Electivire", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Rotom (mow)", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Rotom (frost)", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Giant Galvantula", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Eelektross", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Raichu (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Mega Ampharos Electric (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Shiny Ampharos (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Electivire (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Shiny Eelektross (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Magnezone (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Shiny Pachirisu", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Zebstrika", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Toxtricity", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Eelektross", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Light Ball Pikachu", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Alolan Raichu", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Alolan Graveler", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Electrode", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Hisuian Electrode", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Electabuzz", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Jolteon", tier: "T2", pve: "OTDD", pvp: "OTDD" },
    { name: "Dark Pichu", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Shiny Elekid", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Minun and Plusle", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Luxray", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Pachirisu", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Magnezone", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Rotom", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Zebstrika", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Dedenne", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Vikavolt", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Togedemaru", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Toxtricity", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Toxtricity Low Key Form", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Pikachu", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Raichu", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Magneton", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Jolteon", tier: "T3", pve: "BDD", pvp: "Support" },
    { name: "Lanturn", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Ampharos", tier: "T3", pve: "Tank", pvp: "none" },
    { name: "Manectric", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Galvantula", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Emolga", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Eelektross", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Dedenne", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Togedemaru", tier: "T3", pve: "none", pvp: "BDD" },
  ],
  orebound: [
    { name: "Golden Sudowoodo", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Pupitar", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Hisuian Arcanine", tier: "T1C", pve: "none", pvp: "BDD" },
    { name: "Alolan Golem", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Crystal Onix", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Marowak", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Rhydon", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Aerodactyl", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Golden Steelix", tier: "T1C", pve: "Speedster", pvp: "BDD" },
    { name: "Mega Steelix", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Magcargo", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Tyranitar", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Swampert", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Torterra", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Garchomp", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Rhyperior", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Shiny Gliscor", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Mamoswine", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Golurk", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Bloodmoon Ursaluna", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Marowak (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Rhydon (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Shiny Magcargo (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Torterra (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Rhyperior (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Piloswine (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Tyranitar (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Aerodactyl", tier: "T1H", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Rampardos", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Excadrill", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Krookodile", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Ursaluna", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Mega Barbaracle", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Alolan Graveler", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Sandslash", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Shiny Golem", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Big Onix", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Sudowoodo", tier: "T2", pve: "Speedster", pvp: "none" },
    { name: "Steelix", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Piloswine", tier: "T2", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Donphan", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Tyranitar", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Aggron", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Mega Camerupt", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Cradily", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Flygon", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Armaldo", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Torterra", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Rampardos", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Bastiodon", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Wormadam Ground", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Garchomp", tier: "T2", pve: "BDD", pvp: "BDD" },
    { name: "Hippowdon", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Hippowdon Female", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Gliscor", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Probopass", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Excadrill", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Krookodile", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Carracosta", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Archeops", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Golurk", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Tyrantrum", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Aurorus", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Carbink", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Lycanroc", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Lycanroc Dusk Form", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Lycanroc Midnight Form", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Mudsdale", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Palossand", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Runerigus", tier: "T2", pve: "none", pvp: "Support" },
    { name: "Kleavor", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Nidoqueen", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Nidoking", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Dugtrio", tier: "T3", pve: "Speedster", pvp: "BDD" },
    { name: "Alolan Dugtrio", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Golem", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Rhydon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Omastar", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Kabutops", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Shiny Quagsire", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Magcargo", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Piloswine", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Donphan", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Swampert", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Camerupt", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Lunatone", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Solrock", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Whiscash", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Claydol", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Crustle", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Diggersby", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Barbaracle", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Sandaconda", tier: "T3", pve: "Offensive Tank", pvp: "none" },
  ],
  naturia: [
    { name: "Mega Scizor", tier: "T1A", pve: "BDD/OTDD", pvp: "OTDD" },
    { name: "Shiny Leafeon", tier: "T1B", pve: "BDD/OTDD", pvp: "Offensive Tank" },
    { name: "Mega Venusaur", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Shiny Venusaur", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Shiny Venomoth", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Alolan Exeggutor", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Pinsir", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Pinsir", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Meganium", tier: "T1C", pve: "none", pvp: "Support" },
    { name: "Shiny Ariados", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Scizor", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Mega Heracross", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mega Sceptile", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Torterra", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Abomasnow", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Tangrowth", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Shiny Rotom (mow)", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Giant Galvantula", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Gogoat", tier: "T1C", pve: "OTDD", pvp: "BDD" },
    { name: "Shiny Vikavolt", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Venusaur (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Venomoth (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Meganium (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Ariados (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Tangrowth (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Shiny Gogoat (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Venusaur (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Scyther (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Victreebel", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Scyther", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Tangela", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Mega Meganium", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Sceptile", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Yanmega", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Scolipede", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Beedrill", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Vileplume", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Hisuian Electrode", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Exeggutor", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Scyther", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Pinsir", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Bellossom", tier: "T2", pve: "Speedster", pvp: "OTDD" },
    { name: "Scizor", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Shiny Shuckle", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Heracross", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Ludicolo", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Cacturne", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Cradily", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Armaldo", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Tropius", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Torterra", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Kricketune", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Roserade", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Wormadam Ground", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Wormadam Steel", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Vespiquen", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Abomasnow", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Yanmega", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Scolipede", tier: "T2", pve: "Speedster", pvp: "none" },
    { name: "Whimsicott", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Lilligant", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Escavalier", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Ferrothorn", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Accelgor", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Volcarona", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Gogoat", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Vikavolt", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Frosmoth", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Kleavor", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Venusaur", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Butterfree", tier: "T3", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Beedrill", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Parasect", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Victreebel", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Meganium", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Shiny Ledian", tier: "T3", pve: "Speedster", pvp: "none" },
    { name: "Shiny Jumpluff", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Forretress", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Sceptile", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Beautifly", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiftry", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Breloom", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Ninjask", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Kricketune", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Wormadam", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Leafeon", tier: "T3", pve: "Tank", pvp: "none" },
    { name: "Lilligant", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Crustle", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Galvantula", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Ferrothorn", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Flapple", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Appletun", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Frosmoth", tier: "T3", pve: "Offensive Tank", pvp: "none" },
  ],
  gardestrike: [
    { name: "Shiny Snorlax", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Tauros", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Pidgeot", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Alolan Raticate", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Machamp", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Elite Farfetch'D", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Mega Kangaskhan", tier: "T1C", pve: "none", pvp: "OTDD" },
    { name: "Mega Heracross", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Stantler", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Mega Blaziken", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Slaking", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Infernape", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Lucario", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Porygon-Z", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Gallade", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Audino", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Conkeldurr", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Wyrdeer", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Bloodmoon Ursaluna", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Machamp (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Mega Kangaskhan (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Shiny Infernape (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Mega Lucario Fighting (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Conkeldurr (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Snorlax (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Heracross (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Shiny Heracross", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Hariyama", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Mienshao", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Pyroar", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Barbaracle", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Hawlucha", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Drampa", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Ursaluna", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Champion Poliwrath", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Elite Hitmonlee", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Elite Hitmonchan", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Snorlax", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Girafarig", tier: "T2", pve: "Speedster", pvp: "BDD" },
    { name: "Heracross", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Ursaring", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Smeargle 8", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Elite Hitmontop", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Blissey", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Exploud", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Hariyama", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Mega Medicham", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Zangoose", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Infernape", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Ambipom", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Mega Lopunny", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Munchlax", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Lucario", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Toxicroak", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Lickilicky", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Gallade", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Throh", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Sawk", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Scrafty", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Mienshao", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Braviary", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Pyroar", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Pyroar Female", tier: "T2", pve: "Tank", pvp: "Tank" },
    { name: "Pangoro", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Hawlucha", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Drampa", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Sirfetch'd", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Sneasler", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Pidgeot", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Wigglytuff", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Champion Primeape", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Primeape", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Poliwrath", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Machoke", tier: "T3", pve: "Speedster", pvp: "none" },
    { name: "Machamp", tier: "T3", pve: "BDD", pvp: "OTDD" },
    { name: "Kangaskhan", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Girafarig", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Porygon2", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Smeargle 7", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Miltank", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Blaziken", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Swellow", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Breloom", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Medicham", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Kecleon", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Lopunny", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Purugly", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Lucario", tier: "T3", pve: "Speedster", pvp: "BDD" },
    { name: "Diggersby", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Hawlucha", tier: "T3", pve: "none", pvp: "BDD" },
  ],
  ironhard: [
    { name: "Mega Scizor", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Mega Aggron", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Alolan Sandslash", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Magneton", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Crystal Onix", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Mega Steelix", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Golden Steelix", tier: "T1C", pve: "Speedster", pvp: "BDD" },
    { name: "Shiny Scizor", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Mega Mawile", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Metagross", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Shiny Empoleon", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Bronzong", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Mega Lucario", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Magnezone", tier: "T1C", pve: "OTDD", pvp: "BDD" },
    { name: "Heatran", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Copperajah", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Magneton (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Mega Lucario Steel (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Magnezone (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Copperajah (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Scizor (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Skarmory", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Mawile", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Aggron", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Mega Metagross", tier: "T1H", pve: "Offensive Tank", pvp: "none" },
    { name: "Mega Excadrill", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Aegislash", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Forretress", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Steelix", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Scizor", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Skarmory", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Aggron", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Metang", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Empoleon", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Bastiodon", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Bronzong", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Lucario", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Magnezone", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Probopass", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Excadrill", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Escavalier", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Ferrothorn", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Klinklang", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Aegislash", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Klefki", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Togedemaru", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Perrserker", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Copperajah", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Alolan Dugtrio", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Magneton", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Forretress", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Mawile", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Shiny Lairon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Metang", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Lucario", tier: "T3", pve: "Speedster", pvp: "BDD" },
    { name: "Ferrothorn", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Klinklang", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Bisharp", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Togedemaru", tier: "T3", pve: "none", pvp: "BDD" },
  ],
  wingeon: [
    { name: "Shiny Gyarados", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Dragonair", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Charizard", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Charizard Y", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mega Charizard X", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Shiny Pidgeot", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Elite Farfetch'D", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Shiny Dodrio", tier: "T1C", pve: "none", pvp: "BDD" },
    { name: "Alolan Exeggutor", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Mega Pinsir", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Aerodactyl", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Ampharos", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Mantine", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Kingdra", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Sceptile", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mega Altaria", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Salamence", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Honchkrow", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Garchomp", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Shiny Gliscor", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Mega Charizard X (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Pidgeot (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Elite Farfetch'D (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Dodrio (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Mega Ampharos Dragon (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Mega Altaria Dragon (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Dragonair (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Skarmory (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Clefable", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Pidgeot", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Dragonite", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Feraligatr", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Skarmory", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Skarmory", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Hydreigon", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Hawlucha", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Drampa", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Fearow", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Scyther", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Gyarados", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Dragonite", tier: "T2", pve: "Offensive Tank", pvp: "Offensive Tank" },
    { name: "Shiny Noctowl", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Shiny Crobat", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Shiny Togetic", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Mantine", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Skarmory", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Kingdra", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Flygon", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Tropius", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Staraptor", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Vespiquen", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Drifblim", tier: "T2", pve: "none", pvp: "Support" },
    { name: "Honchkrow", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Garchomp", tier: "T2", pve: "BDD", pvp: "BDD" },
    { name: "Togekiss", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Yanmega", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Gliscor", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Archeops", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Haxorus", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Druddigon", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Braviary", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Hydreigon", tier: "T2", pve: "OTDD", pvp: "OTDD" },
    { name: "Talonflame", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Dragalge", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Tyrantrum", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Hawlucha", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Goodra", tier: "T2", pve: "Tank", pvp: "Tank" },
    { name: "Noivern", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Turtonator", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Drampa", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Charizard", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Butterfree", tier: "T3", pve: "BDD", pvp: "Disrupter" },
    { name: "Pidgeot", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Dragonair", tier: "T3", pve: "BDD", pvp: "BDD" },
    { name: "Crobat", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Togetic", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Xatu", tier: "T3", pve: "Speedster", pvp: "none" },
    { name: "Shiny Jumpluff", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Delibird", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Beautifly", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Swellow", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Pelipper", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Ninjask", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Altaria", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Emolga", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Druddigon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Hawlucha", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Flapple", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Appletun", tier: "T3", pve: "none", pvp: "Tank" },
  ],
  psycraft: [
    { name: "Shiny Alakazam", tier: "T1A", pve: "BDD/OTDD", pvp: "BDD" },
    { name: "Shiny Sylveon", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Alolan Ninetales", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mega Alakazam", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Mr.Mime", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Jynx", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Xatu", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Espeon", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Granbull", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Gardevoir", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Mega Mawile", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Mega Altaria", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Metagross", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Shiny Bronzong", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Gallade", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Audino", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Shiny Delphox", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Wyrdeer", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Mega Alakazam (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Granbull (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Mega Gardevoir (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Mega Altaria Fairy (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Mega Altaria Dragon (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Metagross (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Shiny Gallade (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Wigglytuff (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Slowking (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Clefable", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Starmie", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Meganium", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Gardevoir", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Togekiss", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Shiny Gothitelle", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Alolan Raichu", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Clefable", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Wigglytuff", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Light Abra", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Alakazam", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Galarian Rapidash", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Mega Slowbro", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Hypno", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Exeggutor", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Starmie", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Jynx", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Togetic", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Azumarill", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Slowking", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Wobbuffet", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Girafarig", tier: "T2", pve: "Speedster", pvp: "BDD" },
    { name: "Gardevoir", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Mega Medicham", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Shiny Grumpig", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Shiny Metang", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Bronzong", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Togekiss", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Gallade", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Whimsicott", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Darmanitan", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Gothitelle", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Florges", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Meowstic", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Aromatisse", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Shiny Dedenne", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Shiny Carbink", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Klefki", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Mimikyu", tier: "T2", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Hatterene", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Alcremie", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Clefable", tier: "T3", pve: "Tank", pvp: "none" },
    { name: "Wigglytuff", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Kadabra", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Slowbro", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Starmie", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Mr.Mime", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Togetic", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Xatu", tier: "T3", pve: "Speedster", pvp: "none" },
    { name: "Azumarill", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Espeon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Girafarig", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Granbull", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Mawile", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Medicham", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Grumpig", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Lunatone", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Solrock", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Claydol", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Metang", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Sylveon", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Dedenne", tier: "T3", pve: "none", pvp: "Support" },
  ],
  seavell: [
    { name: "Shiny Gyarados", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Glaceon", tier: "T1B", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Blastoise", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Blastoise", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Alolan Sandslash", tier: "T1C", pve: "OTDD", pvp: "BDD" },
    { name: "Alolan Ninetales", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Tentacruel", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Jynx", tier: "T1C", pve: "BDD", pvp: "Disrupter" },
    { name: "Mega Gyarados", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Feraligatr", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Lanturn", tier: "T1C", pve: "OTDD", pvp: "Disrupter" },
    { name: "Shiny Politoed", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Mantine", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Kingdra", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Swampert", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Milotic", tier: "T1C", pve: "none", pvp: "OTDD" },
    { name: "Shiny Empoleon", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Mega Abomasnow", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mamoswine", tier: "T1C", pve: "OTDD", pvp: "Tank" },
    { name: "Shiny Froslass", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Shiny Rotom (frost)", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Blastoise (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Alolan Ninetales (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Feraligatr (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Politoed (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Milotic (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Empoleon (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Jynx (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Kingdra (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Starmie", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Lapras", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Mega Feraligatr", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Glalie", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Floatzel", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Froslass", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Golduck", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Champion Poliwrath", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Mega Slowbro", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Cloyster", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Shiny Kingler", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Starmie", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Jynx", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Giant Magikarp", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Gyarados", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Lapras", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Vaporeon", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Azumarill", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Slowking", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Piloswine", tier: "T2", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Octillery", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Mantine", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Kingdra", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Ludicolo", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Walrein", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Empoleon", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Floatzel", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Abomasnow", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Weavile", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Galarian Darmanitan", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Galarian Zen Darmanitan", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Carracosta", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Vanilluxe", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Alomomola", tier: "T2", pve: "Support", pvp: "none" },
    { name: "Beartic", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Aurorus", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Avalugg", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Shiny Frosmoth", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Blastoise", tier: "T3", pve: "Tank", pvp: "none" },
    { name: "Golduck", tier: "T3", pve: "Speedster", pvp: "none" },
    { name: "Poliwrath", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Tentacruel", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Slowbro", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Dewgong", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Starmie", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Vaporeon", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Omastar", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Kabutops", tier: "T3", pve: "none", pvp: "Tank" },
    { name: "Feraligatr", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Lanturn", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Azumarill", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Quagsire", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Piloswine", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Shiny Delibird", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Swampert", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Pelipper", tier: "T3", pve: "none", pvp: "Disrupter" },
    { name: "Sharpedo", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Whiscash", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Crawdaunt", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Glalie", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Glaceon", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Froslass", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Barbaracle", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Frosmoth", tier: "T3", pve: "Offensive Tank", pvp: "none" },
  ],
  malefic: [
    { name: "Mega Absol", tier: "T1A", pve: "BDD/OTDD", pvp: "Tank" },
    { name: "Shiny Gengar", tier: "T1B", pve: "BDD/OTDD", pvp: "BDD" },
    { name: "Shiny Venusaur", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Mega Venusaur", tier: "T1C", pve: "BDD", pvp: "Tank" },
    { name: "Alolan Raticate", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Shiny Venomoth", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Tentacruel", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Shiny Muk", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Gengar", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Alolan Marowak", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Mega Gyarados", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Umbreon", tier: "T1C", pve: "none", pvp: "Disrupter" },
    { name: "Mega Houndoom", tier: "T1C", pve: "OTDD", pvp: "OTDD" },
    { name: "Mega Tyranitar", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Mega Sableye", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Mega Banette", tier: "T1C", pve: "BDD", pvp: "BDD" },
    { name: "Shiny Honchkrow", tier: "T1C", pve: "OTDD", pvp: "Offensive Tank" },
    { name: "Dusknoir", tier: "T1C", pve: "BDD", pvp: "Offensive Tank" },
    { name: "Shiny Froslass", tier: "T1C", pve: "BDD", pvp: "OTDD" },
    { name: "Shiny Golurk", tier: "T1C", pve: "none", pvp: "Tank" },
    { name: "Overqwil", tier: "T1C", pve: "none", pvp: "Offensive Tank" },
    { name: "Alolan Raticate (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Tentacruel (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Shiny Muk (TM)", tier: "TM", pve: "Offensive Tank", pvp: "none" },
    { name: "Mega Sableye (TM)", tier: "TM", pve: "Tank", pvp: "none" },
    { name: "Shiny Honchkrow (TM)", tier: "TM", pve: "OTDD", pvp: "none" },
    { name: "Dusknoir (TM)", tier: "TM", pve: "BDD", pvp: "none" },
    { name: "Shiny Crobat (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Weavile (TR)", tier: "TR", pve: "BDD", pvp: "none" },
    { name: "Mega Victreebel", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Weavile", tier: "T1H", pve: "OTDD", pvp: "none" },
    { name: "Mega Froslass", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Scolipede", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Shiny Garbodor", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Zoroark", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Chandelure", tier: "T1H", pve: "BDD", pvp: "none" },
    { name: "Mega Beedrill", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Nidoqueen", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Nidoking", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Dark Abra", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Alolan Muk", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Gengar", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Weezing", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Hisuian Typhlosion", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Shiny Crobat", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Dark Pichu", tier: "T2", pve: "none", pvp: "OTDD" },
    { name: "Misdreavus", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Shiny Qwilfish", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Houndoom", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Tyranitar", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Mightyena", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Shiny Swalot", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Cacturne", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Seviper", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Dusclops", tier: "T2", pve: "Tank", pvp: "none" },
    { name: "Absol", tier: "T2", pve: "OTDD", pvp: "BDD" },
    { name: "Roserade", tier: "T2", pve: "BDD", pvp: "none" },
    { name: "Drifblim", tier: "T2", pve: "none", pvp: "Support" },
    { name: "Mismagius", tier: "T2", pve: "Offensive Tank", pvp: "Offensive Tank" },
    { name: "Honchkrow", tier: "T2", pve: "none", pvp: "Disrupter" },
    { name: "Spiritomb", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Drapion", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Toxicroak", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Weavile", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Scolipede", tier: "T2", pve: "Speedster", pvp: "none" },
    { name: "Krookodile", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Scrafty", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Cofagrigus", tier: "T2", pve: "Offensive Tank", pvp: "none" },
    { name: "Garbodor", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Hydreigon", tier: "T2", pve: "OTDD", pvp: "OTDD" },
    { name: "Golurk", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Pangoro", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Aegislash", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Dragalge", tier: "T2", pve: "none", pvp: "Tank" },
    { name: "Palossand", tier: "T2", pve: "Support Overtime", pvp: "none" },
    { name: "Mimikyu", tier: "T2", pve: "none", pvp: "Offensive Tank" },
    { name: "Toxtricity", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Toxtricity Low Key Form", tier: "T2", pve: "none", pvp: "BDD" },
    { name: "Runerigus", tier: "T2", pve: "none", pvp: "Support" },
    { name: "Sneasler", tier: "T2", pve: "OTDD", pvp: "none" },
    { name: "Venusaur", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Shiny Beedrill", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Arbok", tier: "T3", pve: "Offensive Tank", pvp: "none" },
    { name: "Nidoqueen", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Nidoking", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Alolan Persian", tier: "T3", pve: "Tank", pvp: "none" },
    { name: "Shiny Victreebel", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Tentacruel", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Muk", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiny Haunter", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Crobat", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Umbreon", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Hisuian Qwilfish", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Shiftry", tier: "T3", pve: "none", pvp: "OTDD" },
    { name: "Swalot", tier: "T3", pve: "none", pvp: "Support" },
    { name: "Sharpedo", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Crawdaunt", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Banette", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Froslass", tier: "T3", pve: "BDD", pvp: "none" },
    { name: "Chandelure", tier: "T3", pve: "none", pvp: "Offensive Tank" },
    { name: "Bisharp", tier: "T3", pve: "none", pvp: "BDD" },
    { name: "Cursola", tier: "T3", pve: "BDD", pvp: "none" },
  ],
};

// Mapeamento name → kebab-case id
function toId(name) {
  return name
    .toLowerCase()
    .replace(/'/g, "")
    .replace(/[\(\)]/g, "")
    .replace(/\./g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// Carrega roster atual e pokemon.json pra reusar elements e ids existentes
const existing = JSON.parse(fs.readFileSync(ROSTER_PATH, "utf8"));
const existingByName = new Map(existing.map((p) => [p.name, p]));

// Merge wikiData: name → {tiers per clan, pveRoles, pvpRoles, clans}
const merged = new Map();
for (const [clanName, entries] of Object.entries(wikiData)) {
  for (const entry of entries) {
    let m = merged.get(entry.name);
    if (!m) {
      m = {
        name: entry.name,
        clans: new Set(),
        tiers: [], // {clan, tier}
        pveRoles: new Set(),
        pvpRoles: new Set(),
      };
      merged.set(entry.name, m);
    }
    m.clans.add(clanName);
    m.tiers.push({ clan: clanName, tier: entry.tier });
    const pveR = mapRole(entry.pve);
    const pvpR = mapRole(entry.pvp);
    if (pveR) m.pveRoles.add(pveR);
    if (pvpR) m.pvpRoles.add(pvpR);
  }
}

// Decisão de tier: pega menor rank (T1A é o menor/mais forte)
function pickTier(tiers) {
  return tiers
    .map((t) => t.tier)
    .sort((a, b) => (TIER_RANK[a] ?? 99) - (TIER_RANK[b] ?? 99))[0];
}

// Decisão de role primário (PvE): otdd > burst_dd > offensive_tank > outras
const PVE_ROLE_PRIORITY = ["otdd", "burst_dd", "offensive_tank", "tank", "speedster", "support", "disrupter"];
const PVP_ROLE_PRIORITY = ["otdd", "burst_dd", "offensive_tank", "tank", "speedster", "disrupter", "support"];

function pickRole(roles, priority) {
  if (roles.size === 0) return null;
  for (const r of priority) {
    if (roles.has(r)) return r;
  }
  return null;
}

const newRoster = [];
const seenIds = new Set();
for (const m of merged.values()) {
  const existingPoke = existingByName.get(m.name);
  const id = existingPoke?.id ?? toId(m.name);
  if (seenIds.has(id)) {
    console.warn(`Duplicate id detected: ${id} (${m.name})`);
    continue;
  }
  seenIds.add(id);

  const tier = pickTier(m.tiers);
  const role = pickRole(m.pveRoles, PVE_ROLE_PRIORITY) ?? "burst_dd"; // fallback
  const pvpRole = pickRole(m.pvpRoles, PVP_ROLE_PRIORITY);
  const elements = existingPoke?.elements ?? [];

  newRoster.push({
    id,
    name: m.name,
    tier,
    clans: [...m.clans],
    role,
    pvpRole: pvpRole ?? null,
    elements,
  });
}

// Adiciona pokes existentes do roster que NÃO estão no wiki (edge cases tipo "Crystal Onix")
for (const p of existing) {
  if (!seenIds.has(p.id)) {
    newRoster.push(p);
    seenIds.add(p.id);
  }
}

// Sort por nome
newRoster.sort((a, b) => a.name.localeCompare(b.name));

fs.writeFileSync(ROSTER_PATH, JSON.stringify(newRoster, null, 2) + "\n");
console.log(`Wrote ${newRoster.length} entries to roster.`);
console.log(`OTDD count: ${newRoster.filter((p) => p.role === "otdd").length}`);
console.log(`BDD count: ${newRoster.filter((p) => p.role === "burst_dd").length}`);
console.log(`Offensive tank count: ${newRoster.filter((p) => p.role === "offensive_tank").length}`);
console.log(`Tank count: ${newRoster.filter((p) => p.role === "tank").length}`);
console.log(`Speedster count: ${newRoster.filter((p) => p.role === "speedster").length}`);
console.log(`Support count: ${newRoster.filter((p) => p.role === "support").length}`);
console.log(`Disrupter count: ${newRoster.filter((p) => p.role === "disrupter").length}`);
console.log(`Without elements (need fixing): ${newRoster.filter((p) => p.elements.length === 0).length}`);
